# This workflow will build a Java project with Gradle and cache/restore any dependencies
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle with version 8.10
    - name: Setup Gradle 8.10
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.10'

    # Run Gradle without the Wrapper
    - name: Build with Gradle
      run: gradle build
