# This workflow will build a Java project with Gradle and cache/restore any dependencies
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle 8.10
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.10'

    - name: Build with Gradle
      run: gradle build

    env:
      DISPLAY: ":99.0"

    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        options: -e VNC_SERVER=true -e VNC_PORT=5900

    - name: Start Xvfb
      run: Xvfb $DISPLAY -ac -screen 0 1600x1200x24 > /dev/null 2>&1 &

    - name: Run tests
      run: gradle test

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: app/build/reports/tests/test

  pmd_analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: PMD Static Code Analysis
      uses: pmd/pmd-github-action@v2.0.0
      with:
        rulesets: 'java-basic'
